In [1]:
import pandas as pd

In [31]:
df_wide = pd.read_json('inflation_rate_wide_clean.json')
df_long = pd.read_json('inflation_rate_clean.json')

C:\Users\Honor\AppData\Local\Temp\ipykernel_11344\2627687354.py:1: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df_wide = pd.read_json('inflation_rate_wide_clean.json')
C:\Users\Honor\AppData\Local\Temp\ipykernel_11344\2627687354.py:1: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df_wide = pd.read_json('inflation_rate_wide_clean.json')
C:\Users\Honor\AppData\Local\Temp\ipykernel_11344\2627687354.py:1: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df_wide = pd.read_json('inflation_rate_wide_clean.json')

In [33]:
df_wide.head()

,2024,2023,2022,2021,2020,2019,2018,2017,2016,2015,country_name,country_code
0,45.20,221.34,171.21,154.76,84.86,3.01,6.08,4.32,-0.78,-3.75,Lebanon,LBN
1,58.51,53.86,72.31,19.60,12.28,15.18,16.30,11.10,7.80,7.70,Turkey,TUR
2,28.63,47.64,27.21,11.87,13.45,14.81,16.03,18.22,10.89,6.69,Sierra Leone,SLE
3,32.46,44.58,43.49,43.39,30.59,39.91,18.01,8.04,7.25,12.48,Iran,IRN
4,22.85,38.11,31.26,9.97,9.89,7.14,7.81,12.37,17.45,17.15,Ghana,GHA

In [35]:
df_long.head()

   country_name  year  inflation_rate country_code country_year
0       Lebanon  2019            3.01          LBN      LBN2019
1        Turkey  2019           15.18          TUR      TUR2019
2  Sierra Leone  2019           14.81          SLE      SLE2019
3          Iran  2019           39.91          IRN      IRN2019
4         Ghana  2019            7.14          GHA      GHA2019

In [37]:
df_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 885 entries, 0 to 884
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country_name    885 non-null    object
 1   year            885 non-null    int64
 2   inflation_rate  885 non-null    float64
 3   country_code    885 non-null    object
 4   country_year    885 non-null    object
dtypes: float64(1), int64(1), object(3)
memory usage: 34.7+ KB

In [39]:
df_long_new = df_wide.melt(
    id_vars=["country_name", "country_code"],   # leaving unchanged
    var_name="year",                            # new column name
    value_name="inflation_rate"                 # the value we fill
)

In [41]:
df_long_new.head()

   country_name country_code  year  inflation_rate
0       Lebanon          LBN  2024           45.20
1        Turkey          TUR  2024           58.51
2  Sierra Leone          SLE  2024           28.63
3          Iran          IRN  2024           32.46
4         Ghana          GHA  2024           22.85

In [47]:
df_long_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1770 entries, 0 to 1769
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country_name    1770 non-null   object
 1   country_code    1770 non-null   object
 2   year            1770 non-null   int32
 3   inflation_rate  1770 non-null   float64
dtypes: float64(1), int32(1), object(2)
memory usage: 48.5+ KB

In [45]:
df_long_new["year"] = df_long_new["year"].astype(int)

In [55]:
df_long[
    (df_long["country_name"] == "Lebanon") &
    (df_long["year"] == 2015)
] # should be missing

Empty DataFrame
Columns: [country_name, year, inflation_rate, country_code, country_year]
Index: []

In [57]:
df_long_new[
    (df_long_new["country_name"] == "Lebanon") &
    (df_long_new["year"] == 2015)
] # added successfully

     country_name country_code  year  inflation_rate
1593      Lebanon          LBN  2015           -3.75

In [65]:
df_long_new["country_year"] = (
    df_long_new["country_code"] + df_long_new["year"].astype(str)
)

In [67]:
df_long_new.head()

   country_name country_code  year  inflation_rate country_year
0       Lebanon          LBN  2024           45.20      LBN2024
1        Turkey          TUR  2024           58.51      TUR2024
2  Sierra Leone          SLE  2024           28.63      SLE2024
3          Iran          IRN  2024           32.46      IRN2024
4         Ghana          GHA  2024           22.85      GHA2024

In [71]:
repeat_order = ["country_name",
    "year",
    "inflation_rate",
    "country_code",
    "country_year"]

In [73]:
df_reordered = df_long_new[repeat_order]

In [75]:
df_reordered.head()

   country_name  year  inflation_rate country_code country_year
0       Lebanon  2024           45.20          LBN      LBN2024
1        Turkey  2024           58.51          TUR      TUR2024
2  Sierra Leone  2024           28.63          SLE      SLE2024
3          Iran  2024           32.46          IRN      IRN2024
4         Ghana  2024           22.85          GHA      GHA2024

In [77]:
df_reordered.to_json(
    "inflation_rate_clean.json",
    orient="records",
    indent=2,
    force_ascii=False
)